"""
Investor pack exporter — collects all available project artifacts and
renders them as a structured markdown document.

Minimum required artifacts (returns 409 if missing):
  - validation_report
  - business_model_canvas
  - financial_model
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import InsufficientArtifactsError
from app.repositories.artifact_repository import ArtifactRepository

# Minimum artifacts required for a valid investor pack
REQUIRED_ARTIFACT_TYPES: list[str] = [
    "validation_report",
    "business_model_canvas",
    "financial_model",
]

# All possible artifact types in display order
ARTIFACT_SECTIONS: list[tuple[str, str]] = [
    ("validation_report",    "1. Idea Validation"),
    ("market_analysis",      "2. Market Research"),
    ("business_model_canvas","3. Business Model Canvas"),
    ("product_roadmap",      "4. Product Strategy"),
    ("architecture_doc",     "5. Technical Architecture"),
    ("financial_model",      "6. Financial Model"),
    ("marketing_plan",       "7. Marketing Strategy"),
    ("investor_deck_outline","8. Investor Documentation"),
]


def _render_value(value: Any, indent: int = 0) -> str:
    """Recursively render a JSON value as readable markdown text."""
    prefix = "  " * indent
    if isinstance(value, dict):
        lines = []
        for k, v in value.items():
            label = k.replace("_", " ").title()
            if isinstance(v, (dict, list)):
                lines.append(f"{prefix}**{label}:**")
                lines.append(_render_value(v, indent + 1))
            else:
                lines.append(f"{prefix}**{label}:** {v}")
        return "\n".join(lines)
    elif isinstance(value, list):
        if not value:
            return f"{prefix}_(none)_"
        lines = []
        for item in value:
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}-")
                lines.append(_render_value(item, indent + 1))
            else:
                lines.append(f"{prefix}- {item}")
        return "\n".join(lines)
    else:
        return f"{prefix}{value}"


def _render_artifact_section(title: str, content_json: dict) -> str:
    """Render a single artifact as a markdown section."""
    lines: list[str] = [f"## {title}", ""]
    lines.append(_render_value(content_json))
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


async def generate_investor_pack(
    project_id: uuid.UUID,
    project_name: str,
    idea_brief: str,
    session: AsyncSession,
    export_dir: str,
) -> str:
    """
    Collect all available artifacts for a project and render as structured markdown.

    Saves the file to {export_dir}/{project_id}_{timestamp}.md

    Args:
        project_id:   UUID of the project.
        project_name: Human-readable project name.
        idea_brief:   The project idea brief text.
        session:      AsyncSession for DB access.
        export_dir:   Directory to save the file (from settings.export_dir).

    Returns:
        Absolute file path of the saved markdown export.

    Raises:
        InsufficientArtifactsError: If any of the minimum required artifacts are missing.
    """
    repo = ArtifactRepository(session)

    # ── Load all artifacts ────────────────────────────────────────────────
    artifact_map: dict[str, dict] = {}
    all_artifacts = await repo.list_by_project(project_id, skip=0, limit=100)
    for artifact in all_artifacts:
        artifact_map[artifact.artifact_type] = artifact.content_json or {}

    # ── Check minimum requirements ────────────────────────────────────────
    missing = [t for t in REQUIRED_ARTIFACT_TYPES if t not in artifact_map]
    if missing:
        raise InsufficientArtifactsError(missing)

    # ── Build markdown ────────────────────────────────────────────────────
    now = datetime.now(timezone.utc)
    timestamp_display = now.strftime("%B %d, %Y at %H:%M UTC")

    lines: list[str] = [
        f"# {project_name} — Investor Pack",
        f"_Generated: {timestamp_display}_",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        idea_brief,
        "",
        "---",
        "",
    ]

    for artifact_type, section_title in ARTIFACT_SECTIONS:
        content = artifact_map.get(artifact_type)
        if content:
            lines.append(_render_artifact_section(section_title, content))

    lines.append("---")
    lines.append("")
    lines.append("*Generated by FoundrAI — AI-Powered Startup Studio*")

    markdown_content = "\n".join(lines)

    # ── Save to disk ──────────────────────────────────────────────────────
    os.makedirs(export_dir, exist_ok=True)
    timestamp_file = now.strftime("%Y%m%d_%H%M%S")
    filename = f"{project_id}_{timestamp_file}.md"
    file_path = Path(export_dir) / filename

    file_path.write_text(markdown_content, encoding="utf-8")

    return str(file_path)
